# Generated by Django 3.0.7 on 2024-10-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phtoto', models.ImageField(upload_to=None)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('google', models.URLField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
