# Generated by Django 3.0.7 on 2024-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, choices=[('أبها', 'أبها'), ('الباحة', 'الباحة'), ('الدمام', 'الدمام'), ('الرياض', 'الرياض'), ('المدينة المنورة', 'المدينة المنورة'), ('بريدة', 'بريدة'), ('تبوك', 'تبوك'), ('جازان', 'جازان'), ('سكاكا', 'سكاكا'), ('عرار', 'عرار'), ('مكة المكرمة', 'مكة المكرمة'), ('نجران', 'نجران'), ('يشيد', 'يشيد')], max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('model', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], max_length=250, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.IntegerField(max_length=10)),
                ('description', models.TextField(max_length=5000)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/<django.db.models.fields.CharField>')),
                ('car_photo_1', models.ImageField(blank=True, null=True, upload_to='photos/cars/<django.db.models.fields.CharField>')),
                ('car_photo_2', models.ImageField(blank=True, null=True, upload_to='photos/cars/<django.db.models.fields.CharField>')),
                ('car_photo_3', models.ImageField(blank=True, null=True, upload_to='photos/cars/<django.db.models.fields.CharField>')),
                ('car_photo_4', models.ImageField(blank=True, null=True, upload_to='photos/cars/<django.db.models.fields.CharField>')),
                ('car_photo_5', models.ImageField(blank=True, null=True, upload_to='photos/cars/<django.db.models.fields.CharField>')),
                ('features', models.CharField(blank=True, choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=250, null=True)),
                ('body_style', models.CharField(blank=True, max_length=250, null=True)),
                ('engine', models.CharField(blank=True, max_length=250, null=True)),
                ('transmission', models.CharField(blank=True, max_length=250, null=True)),
                ('interior', models.CharField(blank=True, max_length=250, null=True)),
                ('miles', models.IntegerField(blank=True, max_length=250, null=True)),
                ('doors', models.IntegerField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=250, null=True)),
                ('passengers', models.IntegerField(blank=True, max_length=250, null=True)),
                ('vin_no', models.CharField(blank=True, max_length=250, null=True)),
                ('milage', models.IntegerField(blank=True, max_length=250, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=250, null=True)),
                ('no_of_owner', models.IntegerField(blank=True, max_length=250, null=True)),
                ('is_features', models.BooleanField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
