# Generated by Django 5.1.2 on 2024-10-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_description_alter_car_milage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount',
            field=models.IntegerField(default=100),
        ),
    ]
