# Generated by Django 5.1.2 on 2024-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_car_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount',
            field=models.IntegerField(default=100),
        ),
    ]
