# Generated by Django 5.1.2 on 2024-10-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='discount',
        ),
    ]
